SELECT *,
CASE STATUS
	WHEN 'A' THEN 'CONTRACT FINISHED NO PROBLEMS'
	WHEN 'B' THEN 'CONTRACT FINISHED LOAN NOT PAYED'
	WHEN 'C' THEN 'RUNNING CONTRACT OK SO FAR'
	ELSE 'RUNNING CONTRACT CLIENT IN DEBT'
END
FROM LOAN;